- platform: template
  covers:
    salon_cover:
      device_class: curtain
      friendly_name: "Salon cover"
      unique_id: salon_cover
      value_template: "{{ state_attr('cover.salon_curtain', 'current_position') | int > 0 }}"
      position_template: "{{ 100 - state_attr('cover.salon_curtain', 'current_position') | int }}"
      open_cover:
        action: cover.close_cover
        entity_id: "cover.salon_curtain"
      close_cover:
        action: cover.open_cover
        entity_id: "cover.salon_curtain"
      stop_cover:
        action: cover.stop_cover
        entity_id: "cover.salon_curtain"
