input_text:
  prev_sunrise:
    initial: "{{state_attr('sun.sun', 'next_rising')}}"

script:
  cover_schedule_get_cover_position:
    fields:
      event_time:
        description: "Time in string format"
      room_name:
        description: "Room name"
    sequence:
      - variables:
          prev_sunrise: "{{ states('input_text.prev_sunrise') }}"
          next_sunrise: "{{ state_attr('sun.sun', 'next_rising') }}"
          next_sunset: "{{ state_attr('sun.sun', 'next_setting') }}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ as_datetime(next_sunrise) > as_datetime(next_sunset) }}"
            sequence:
              - action: calendar.get_events
                target:
                  entity_id: 
                    - calendar.sercan
                    - calendar.melike
                    - calendar.misafir
                data:
                  start_date_time: "{{ event_time | as_datetime }}"
                  duration:
                    hours: 0
                    minutes: 0
                    seconds: 1
                response_variable: events
              - variables:
                  cover_position: >
                    {% set ns = namespace(found_events=[]) %}
                    {% for event in events.values()
                                    | map(attribute="events")
                                    | sum(start=[])
                                    | list %}
                      {% if event.start | as_datetime < prev_sunrise | as_datetime 
                        and event.end | as_datetime > prev_sunrise | as_datetime 
                        and (event.description | from_json)["room_name"] == room_name %}
                          {% set ns.found_events = ns.found_events + [event] %}
                      {% endif%}
                    {% endfor %}
                    {{ { 'result': ns.found_events | count == 0} }}
        default:
          - variables:
              cover_position: "{{ {'result': false} }}"
      - stop:
        response_variable: cover_position
  cover_schedule_set_cover_position:
    fields:
      room_id:
        description: "Room id"
      position:
        description: "True for open, false for close"
    sequence:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ position }}"
            sequence:
              - action: cover.open_cover
                metadata: {}
                data: {}
                target:
                  area_id: "{{ room_id }}"
          - conditions:
            sequence:
              - action: cover.close_cover
                metadata: {}
                data: {}
                target:
                  area_id: "{{ room_id }}"
automation:
  - id: cover_schedule
    alias: cover_schedule
    description: ""
    triggers:
      - trigger: sun
        event: sunset
        offset: 10
        id: sunset
      - trigger: sun
        event: sunrise
        offset: 10
        id: sunrise
      - trigger: sun
        event: sunrise
        offset: -10
        id: pre_sunrise
      - trigger: calendar
        entity_id: calendar.sercan
        event: end
        offset: "0:0:0"
        id: event_end
      - trigger: calendar
        entity_id: calendar.melike
        event: end
        offset: "0:0:0"
        id: event_end
      - trigger: calendar
        entity_id: calendar.misafir
        event: end
        offset: "0:0:0"
        id: event_end
    conditions: []
    actions:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - pre_sunrise
            sequence:
              - action: input_text.set_value
                data:
                  entity_id: input_text.prev_sunrise
                  value: "{{ state_attr('sun.sun', 'next_rising') }}"
          - conditions:
              - condition: trigger
                id:
                  - event_end
            sequence:
              - variables:
                  room_name: "{{ (trigger.calendar_event.description | from_json)['room_name'] }}"
              - action: script.cover_schedule_get_cover_position
                data:
                  event_time: "{{ trigger.calendar_event.end }}"
                  room_name: "{{ room_name }}"
                response_variable: is_open
              - action: script.cover_schedule_set_cover_position
                data:
                  position: "{{ is_open.result }}"
                  room_id: "{{ room_name | area_id }}"
              - delay: 120
        default:
          - repeat:
              count: "{{ areas() | length }}"
              sequence:
                - variables:
                    room_id: "{{ areas()[repeat.index-1] }}"
                - action: script.cover_schedule_get_cover_position
                  data:
                    event_time: "{{ now() }}"
                    room_name: "{{ room_id | area_name }}"
                  response_variable: is_open
                - action: script.cover_schedule_set_cover_position
                  data:
                    position: "{{ is_open.result }}"
                    room_id: "{{ room_id }}"
          - delay: 120
    mode: queued
