automation:
  - id: cover_schedule
    alias: cover_schedule
    description: ""
    triggers:
      - trigger: sun
        event: sunset
        offset: 0
        id: sunset
      - trigger: sun
        event: sunrise
        offset: 0
        id: sunrise
      - trigger: calendar
        entity_id: calendar.sercan
        event: end
        offset: "0:0:0"
        id: event_end
      - trigger: calendar
        entity_id: calendar.melike
        event: end
        offset: "0:0:0"
        id: event_end
      - trigger: calendar
        entity_id: calendar.misafir
        event: end
        offset: "0:0:0"
        id: event_end
    conditions: []
    actions:
      - action: calendar.get_events
        target:
          entity_id: >-
            {{ states.calendar | map(attribute='entity_id') | list }}
        data:
          start_date_time: "{{ now() }}"
          duration:
            hours: 0
            minutes: 0
            seconds: 1
        response_variable: active_events
      - variables:
          sleep_rooms: >
            {% set all_events = active_events.values() | map(attribute='events') | sum(start=[]) | list %}
            {% set ns = namespace(sleep_rooms=[]) %}
            {% for event in all_events %}
              {% set desc = event.description | from_json %}
              {% if as_timestamp(event.start) <= as_timestamp(now()) 
                and as_timestamp(event.end) > as_timestamp(now()) %}
                {% set ns.sleep_rooms = ns.sleep_rooms + [area_id(desc['room_name'])] %}
              {% endif %}
            {% endfor %}
            {{ ns.sleep_rooms }}
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - event_end
            sequence:
              - action: cover.open_cover
                metadata: {}
                data: {}
                target:
                  area_id: "{{ sleep_rooms }}"
              - delay: 120
          - conditions:
              - condition: trigger
                id:
                  - sunset
            sequence:
              - action: cover.close_cover
                metadata: {}
                data: {}
                target:
                  area_id: "{{ areas() | list }}"
          - conditions:
              - condition: trigger
                id:
                  - sunrise
            sequence:
              - action: cover.open_cover
                metadata: {}
                data: {}
                target:
                  area_id: "{{ areas() | reject('in', sleep_rooms) | list }}"
    mode: queued
