template:
  - sensor:
      - name: bebek_thermostat
        unique_id: bebek_thermostat
        unit_of_measurement: "°C"
        state: "{{ state_attr('climate.bebek_climate', 'current_temperature') }}"
        availability: "{{ states('climate.bebek_climate') != 'unavailable' }}"
        device_class: temperature

input_number:
  bebek_thermostat:
    name: bebek_thermostat
    initial: 0
    min: 0
    max: 100
    step: 1

climate:
  - platform: smart_thermostat
    name: bebek_thermostat
    unique_id: bebek_thermostat
    heater: input_number.bebek_thermostat
    target_sensor: sensor.bebek_thermostat
    target_temp: 19
    keep_alive:
      seconds: 60
    kp: 6
    ki: 2
    kd: 0
    min_cycle_duration: 10
    pwm: 0
    min_temp: 4
    max_temp: 35

automation:
  - alias: "bebek thermostat automation"
    id: "bebek_thermostat_automation"
    use_blueprint:
      path: gungorser/thermostat.yaml
      input:
        pidvalue: input_number.bebek_thermostat
        valve_opening: number.bebek_climate_valve_opening_degree
        valve_closing: number.bebek_climate_valve_closing_degree
        valve: climate.bebek_climate
        thermostat: climate.bebek_thermostat