template:
  - sensor:
      - name: melike_thermostat
        unique_id: melike_thermostat
        unit_of_measurement: "°C"
        state: "{{ state_attr('climate.melike_climate', 'current_temperature') }}"
        availability: "{{ states('climate.melike_climate') != 'unavailable' }}"
        device_class: temperature

input_number:
  melike_thermostat:
    name: melike_thermostat
    initial: 0
    min: 0
    max: 100
    step: 1

climate:
  - platform: smart_thermostat
    name: melike_thermostat
    unique_id: melike_thermostat
    heater: input_number.melike_thermostat
    target_sensor: sensor.melike_thermostat
    target_temp: 19
    keep_alive:
      seconds: 60
    kp: 60
    ki: 0.01
    kd: 2000
    min_cycle_duration: 10
    pwm: 0
    min_temp: 4
    max_temp: 35

automation:
  - alias: "melike thermostat automation"
    id: "melike_thermostat_automation"
    use_blueprint:
      path: gungorser/thermostat.yaml
      input:
        pidvalue: input_number.melike_thermostat
        valve_opening: number.melike_climate_valve_opening_degree
        valve_closing: number.melike_climate_valve_closing_degree
        valve: climate.melike_climate
        thermostat: climate.melike_thermostat