template:
  - sensor:
      - name: sercan_thermostat
        unique_id: sercan_thermostat
        unit_of_measurement: "°C"
        state: "{{ state_attr('climate.sercan_climate', 'current_temperature') }}"
        availability: "{{ states('climate.sercan_climate') != 'unavailable' }}"
        device_class: temperature

input_number:
  sercan_thermostat:
    name: sercan_thermostat
    initial: 0
    min: 0
    max: 100
    step: 1

climate:
  - platform: smart_thermostat
    name: sercan_thermostat
    unique_id: sercan_thermostat
    heater: input_number.sercan_thermostat
    target_sensor: sensor.sercan_thermostat
    target_temp: 19
    keep_alive:
      seconds: 60
    kp: 40
    ki: 0.02
    kd: 2000
    min_cycle_duration: 10
    pwm: 0
    min_temp: 4
    max_temp: 35

automation:
  - alias: "sercan thermostat automation"
    id: "sercan_thermostat_automation"
    use_blueprint:
      path: gungorser/thermostat.yaml
      input:
        pidvalue: input_number.sercan_thermostat
        valve_opening: number.sercan_climate_valve_opening_degree
        valve_closing: number.sercan_climate_valve_closing_degree
        valve: climate.sercan_climate
        thermostat: climate.sercan_thermostat
