template:
  - sensor:
      - name: misafir_thermostat
        unique_id: misafir_thermostat
        unit_of_measurement: "°C"
        state: "{{ state_attr('climate.misafir_climate', 'current_temperature') }}"
        availability: "{{ states('climate.misafir_climate') != 'unavailable' }}"
        device_class: temperature

input_number:
  misafir_thermostat:
    name: misafir_thermostat
    initial: 0
    min: 0
    max: 100
    step: 1


climate:
  - platform: smart_thermostat
    name: misafir_thermostat
    unique_id: misafir_thermostat
    heater: input_number.misafir_thermostat
    target_sensor: sensor.misafir_thermostat
    target_temp: 19
    keep_alive:
      seconds: 60
    kp: 6
    ki: 2
    kd: 0
    min_cycle_duration: 10
    pwm: 0
    min_temp: 4
    max_temp: 35

automation:
  - alias: "misafir thermostat automation"
    id: "misafir_thermostat_automation"
    use_blueprint:
      path: gungorser/thermostat.yaml
      input:
        pidvalue: input_number.misafir_thermostat
        valve_opening: number.misafir_climate_valve_opening_degree
        valve_closing: number.misafir_climate_valve_closing_degree
        valve: climate.misafir_climate
        thermostat: climate.misafir_thermostat