blueprint:
  name: light_with_sensor
  description: Light sensor automation
  domain: automation
  input:
    light:
      name: light
      selector:
        entity:
          domain: light
    sensor:
      name: Occupancy Sensor
      description: The sensor to detect movement
      selector:
        entity:
          domain: binary_sensor

alias: light_with_sensor

trigger:
  - platform: state
    entity_id: !input sensor
    from: "off"
    to: "on"
    id: "on"
  - platform: state
    entity_id: !input sensor
    from: "on"
    to: "off"
    id: "off"
  - platform: state
    entity_id: !input light
    id: "light"
variables:
  light: !input light
  name: "{{ light.split('.')[1] }}"
  brightness: 125
  transition: 2.0
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "on"
          - condition: state
            entity_id: sun.sun
            state: "below_horizon"
        sequence:
          - action: scene.create
            data:
              scene_id: "{{name}}"
              snapshot_entities:
                - !input light
          - action: light.turn_on
            metadata: {}
            data:
              brightness: "{{brightness}}"
              transition: "{{transition}}"
            target:
              entity_id: !input light
          - delay:
              hours: 0
              minutes: 0
              seconds: 1
              milliseconds: 0
      - conditions:
          - condition: trigger
            id: "light"
        sequence:
          - action: scene.create
            data:
              scene_id: "{{name}}"
              snapshot_entities:
                - !input light
      - conditions:
          - condition: trigger
            id: "off"
        sequence:
          - action: scene.turn_on
            target:
              entity_id: "{{'scene.'+name}}"

mode: single
