blueprint:
  name: pushbutton
  description: pushbutton automation
  domain: automation
  input:
    room:
      name: Room
      selector:
        area:
    device:
      name: Push Button Device
      description: Count of the buttons in the device
      selector:
        device:
          entity:
            domain: sensor
    button1:
      name: Button 1 function
      selector:
        select:
          options:
            - none
            - light
            - climate
            - cover
    button2:
      name: Button 2 function
      selector:
        select:
          options:
            - none
            - light
            - climate
            - cover
    button3:
      name: Button 3 function
      selector:
        select:
          options:
            - none
            - light
            - climate
            - cover

alias: Roomstate

trigger:
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: "single"
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: "double"
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: "hold"
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: "1_single"
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: "1_double"
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: "1_hold"
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: "2_single"
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: "2_double"
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: "2_hold"
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: "3_single"
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: "3_double"
  - platform: device
    domain: mqtt
    device_id: !input device
    type: action
    subtype: "3_hold"

variables:
  room: !input room
  button1: !input button1
  button2: !input button2
  button3: !input button3
  transition: 1.0

  lights: >-
    {{  states.light 
      | selectattr('entity_id', 'in', area_entities(room)) 
      | map(attribute='entity_id') 
      | list }}
  climates: >-
    {{  states.climate 
      | selectattr('entity_id', 'in', area_entities(room)) 
      | map(attribute='entity_id') 
      | list }}
  covers: >-
    {{  states.cover 
      | selectattr('entity_id', 'in', area_entities(room)) 
      | map(attribute='entity_id') 
      | list }}
  functions: >-
    {{ {
      button1: {'single':'single', 'double':'double', 'hold': 'hold', '1_single':'single', '1_double': 'double', '1_hold': 'hold'},
      button2: {'2_single':'single', '2_double':'double', '2_hold': 'hold'},
      button3: {'3_single':'single', '3_double':'double', '3_hold': 'hold'}
    } }}
action:
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ 'light' in functions and trigger.payload in functions['light'] }}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >-
                      {{ states.light
                        | selectattr('entity_id', 'in', lights)
                        | rejectattr('state', 'eq', 'off')
                        | list | count > 0
                      }}
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: >-
                              {{ functions['light'][trigger.payload] == 'hold' }}
                        sequence:
                          - action: light.turn_on
                            metadata: {}
                            data:
                              rgb_color: >
                                {% set red = state_attr(lights[0], 'rgb_color')[0] %}
                                {% set green = state_attr(lights[0], 'rgb_color')[1] %}
                                {% set blue = state_attr(lights[0], 'rgb_color')[2] %}
                                {% if green==0 and blue==0 %} 
                                {{ [red, red, red] }}
                                {% else %}
                                {{ [red, 0, 0] }} 
                                {% endif %}
                              transition: 1
                            target: "{{ {'entity_id': lights} }}"
                    default:
                      - action: light.turn_off
                        metadata: {}
                        data:
                          transition: "{{transition}}"
                        target: "{{ {'entity_id': lights} }}"
              - conditions:
                  - condition: template
                    value_template: >-
                      {{ functions['light'][trigger.payload] == 'single' }}
                sequence:
                  - action: light.turn_on
                    metadata: {}
                    data:
                      brightness: 255
                      transition: 1
                    target: "{{ {'entity_id': lights} }}"
              - conditions:
                  - condition: template
                    value_template: >-
                      {{ functions['light'][trigger.payload] == 'double' }}
                sequence:
                  - action: light.turn_on
                    metadata: {}
                    data:
                      transition: "{{transition}}"
                      brightness: 25
                    target: "{{ {'entity_id': lights} }}"
      - conditions:
          - condition: template
            value_template: >-
              {{ 'climate' in functions and trigger.payload in functions['climate'] }}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >-
                      {{ functions['climate'][trigger.payload] == 'single'}}
                sequence:
                  - action: climate.turn_on
                    metadata: {}
                    data: {}
                    target: "{{ {'entity_id': climates} }}"
                  - action: script.blink_light
                    data:
                      lights: "{{ lights }}"
                      color:
                        - 255
                        - 0
                        - 0
              - conditions: []
                sequence:
                  - action: climate.turn_off
                    metadata: {}
                    data: {}
                    target: "{{ {'entity_id': climates} }}"
                  - action: script.blink_light
                    data:
                      lights: "{{ lights }}"
                      color:
                        - 0
                        - 0
                        - 255
      - conditions:
          - condition: template
            value_template: >-
              {{ 'cover' in functions and trigger.payload in functions['cover'] }}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >-
                      {{ functions['cover'][trigger.payload] == 'single'}}
                sequence:
                  - action: cover.open_cover
                    metadata: {}
                    data: {}
                    target: "{{ {'entity_id': covers} }}"
              - conditions: []
                sequence:
                  - action: cover.close_cover
                    metadata: {}
                    data: {}
                    target: "{{ {'entity_id': covers} }}"
mode: single
