automation:
  - id: "banyo_humidity"
    alias: banyo_humidity
    mode: single
    triggers:
      - trigger: template
        value_template: "{{ states('sensor.banyo_moisture_humidity') | float(0) > 35 }}"
        id: "on"
      - trigger: template
        value_template: "{{ states('sensor.banyo_moisture_humidity') | float(0) <= 35 }}"
        id: "off"
    conditions: []
    actions:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - "on"
            sequence:
              - action: fan.turn_on
                metadata: {}
                data: {}
                target:
                  entity_id: fan.banyo_fan
          - conditions: []
            sequence:
              - action: fan.turn_off
                metadata: {}
                data: {}
                target:
                  entity_id: fan.banyo_fan
