automation:
  - id: "kat1_coverclose"
    alias: kat1_coverclose
    description: ""
    triggers:
      - domain: mqtt
        device_id: 1d49a19304191ce333202639e9ed74d5
        type: action
        subtype: 1_hold
        trigger: device
        id: button
      - domain: mqtt
        device_id: d3fd09e3b60a91f37e64b9137c1bba7b
        type: action
        subtype: 3_hold
        trigger: device
        id: button
      - domain: mqtt
        device_id: 3b076af749562b3dfa18416768178b40
        type: action
        subtype: 2_hold
        trigger: device
        id: button
    conditions: []
    actions:
      - choose:
          - conditions:
              - condition: template
                value_template:
                  "{{ devices | map('states') | reject('eq', 'closed')
                  | list | count > 0 }}"
            sequence:
              - action: scene.create
                metadata: {}
                data:
                  scene_id: kat1_coverclose
                  snapshot_entities: "{{devices}}"
              - action: cover.close_cover
                metadata: {}
                data: {}
                target:
                  entity_id: "{{devices}}"
          - conditions: []
            sequence:
              - action: scene.turn_on
                metadata: {}
                data: {}
                target:
                  entity_id: scene.kat1_coverclose
    variables:
      devices: "{{ floor_areas('1_kat') | map('area_entities') | sum(start=[]) |
        select('in', states.cover | map(attribute='entity_id')| list)| list}}"
    mode: single
