automation:
  - alias: koridor0_lightsensor
    id: koridor0_lightsensor
    description: ""
    use_blueprint:
      path: gungorser/light_with_sensor.yaml
      input:
        light: light.koridor0_light
        sensor: binary_sensor.koridor0_sensor_occupancy

  - alias: koridor1_lightsensor
    id: koridor1_lightsensor
    description: ""
    use_blueprint:
      path: gungorser/light_with_sensor.yaml
      input:
        light: light.koridor1_light
        sensor: binary_sensor.koridor1_sensor_occupancy

  - alias: koridor2_lightsensor
    id: koridor2_lightsensor
    description: ""
    use_blueprint:
      path: gungorser/light_with_sensor.yaml
      input:
        light: light.koridor1_light
        sensor: binary_sensor.koridor1_sensor_occupancy
