template:
  - sensor:
      - &thermostat_sensor_defaults
        unit_of_measurement: "°C"
        # Replace climate entity with the target entity
        # state: "{{ state_attr(climate_entity, 'current_temperature') | default('unknown') }}"
        # availability: "{{ states(climate_entity) != 'unavailable' }}"
        device_class: temperature
        icon: mdi:thermometer
      - <<: *thermostat_sensor_defaults
        unique_id: sercan_thermostat_temp
        state: "{{ state_attr('climate.sercan_thermostat', 'current_temperature') | default('unknown') }}"
        availability: "{{ states('climate.sercan_thermostat') != 'unavailable' }}"
      - <<: *thermostat_sensor_defaults
        unique_id: melike_thermostat_temp
        state: "{{ state_attr('climate.melike_thermostat', 'current_temperature') | default('unknown') }}"
        availability: "{{ states('climate.melike_thermostat') != 'unavailable' }}"
      - <<: *thermostat_sensor_defaults
        unique_id: bebek_thermostat_temp
        state: "{{ state_attr('climate.bebek_thermostat', 'current_temperature') | default('unknown') }}"
        availability: "{{ states('climate.bebek_thermostat') != 'unavailable' }}"
      - <<: *thermostat_sensor_defaults
        unique_id: misafir_thermostat_temp
        state: "{{ state_attr('climate.misafir_thermostat', 'current_temperature') | default('unknown') }}"
        availability: "{{ states('climate.misafir_thermostat') != 'unavailable' }}"
      - <<: *thermostat_sensor_defaults
        unique_id: yatak_thermostat_temp
        state: "{{ state_attr('climate.yatak_thermostat', 'current_temperature') | default('unknown') }}"
        availability: "{{ states('climate.yatak_thermostat') != 'unavailable' }}"

input_number:
  thermostat_defaults: &input_number_defaults
    initial: 0
    min: 0
    max: 100
    step: 1
  sercan_thermostat:
    <<: *input_number_defaults
  melike_thermostat:
    <<: *input_number_defaults
  bebek_thermostat:
    <<: *input_number_defaults
  misafir_thermostat:
    <<: *input_number_defaults
  yatak_thermostat:
    <<: *input_number_defaults

climate:
  - &thermostat_defaults
    platform: smart_thermostat
    target_temp: 19
    keep_alive:
      seconds: 60
    min_cycle_duration: 10
    pwm: 0
    min_temp: 7
    max_temp: 35
  - <<: *thermostat_defaults
    unique_id: sercan_thermostat
    heater: input_number.sercan_thermostat
    target_sensor: sensor.sercan_thermostat
    kp: 40
    ki: 0.02
    kd: 2000
  - <<: *thermostat_defaults
    unique_id: yatak_thermostat
    heater: input_number.yatak_thermostat
    target_sensor: sensor.yatak_thermostat
    kp: 40
    ki: 0.02
    kd: 2000
  - <<: *thermostat_defaults
    unique_id: melike_thermostat
    heater: input_number.melike_thermostat
    target_sensor: sensor.melike_thermostat
    kp: 40
    ki: 0.02
    kd: 2000
  - <<: *thermostat_defaults
    unique_id: misafir_thermostat
    heater: input_number.misafir_thermostat
    target_sensor: sensor.misafir_thermostat
    kp: 40
    ki: 0.02
    kd: 2000
  - <<: *thermostat_defaults
    unique_id: bebek_thermostat
    heater: input_number.bebek_thermostat
    target_sensor: sensor.bebek_thermostat
    kp: 40
    ki: 0.02
    kd: 2000

automation:
  - alias: "sercan thermostat automation"
    id: "sercan_thermostat_automation"
    use_blueprint:
      path: gungorser/thermostat.yaml
      input:
        pidvalue: input_number.sercan_thermostat
        valve_opening: number.sercan_climate_valve_opening_degree
        valve_closing: number.sercan_climate_valve_closing_degree
        valve: climate.sercan_climate
        thermostat: climate.sercan_thermostat
  - alias: "melike thermostat automation"
    id: "melike_thermostat_automation"
    use_blueprint:
      path: gungorser/thermostat.yaml
      input:
        pidvalue: input_number.melike_thermostat
        valve_opening: number.melike_climate_valve_opening_degree
        valve_closing: number.melike_climate_valve_closing_degree
        valve: climate.melike_climate
        thermostat: climate.melike_thermostat
  - alias: "misafir thermostat automation"
    id: "misafir_thermostat_automation"
    use_blueprint:
      path: gungorser/thermostat.yaml
      input:
        pidvalue: input_number.misafir_thermostat
        valve_opening: number.misafir_climate_valve_opening_degree
        valve_closing: number.misafir_climate_valve_closing_degree
        valve: climate.misafir_climate
        thermostat: climate.misafir_thermostat
  - alias: "yatak thermostat automation"
    id: "yatak_thermostat_automation"
    use_blueprint:
      path: gungorser/thermostat.yaml
      input:
        pidvalue: input_number.yatak_thermostat
        valve_opening: number.yatak_climate_valve_opening_degree
        valve_closing: number.yatak_climate_valve_closing_degree
        valve: climate.yatak_climate
        thermostat: climate.yatak_thermostat
  - alias: "bebek thermostat automation"
    id: "bebek_thermostat_automation"
    use_blueprint:
      path: gungorser/thermostat.yaml
      input:
        pidvalue: input_number.bebek_thermostat
        valve_opening: number.bebek_climate_valve_opening_degree
        valve_closing: number.bebek_climate_valve_closing_degree
        valve: climate.bebek_climate
        thermostat: climate.bebek_thermostat
