homeassistant:
  packages: !include_dir_named gungors/packages/thermostats

automation:
  - alias: "thermostat_switch"
    id: "thermostat_switch"
    description: ""
    triggers:
      - value_template: |-
          {{ ['number.sercan_climate_valve_opening_degree',
              'number.yatak_climate_valve_opening_degree',
              'number.melike_climate_valve_opening_degree',
              'number.bebek_climate_valve_opening_degree',
              'number.misafir_climate_valve_opening_degree'] 
            | map('states')  
            | select('is_number')
            | map('float') | max > 0 }}
        trigger: template
        id: heat
      - value_template: |-
          {{ ['number.sercan_climate_valve_opening_degree',
              'number.yatak_climate_valve_opening_degree',
              'number.melike_climate_valve_opening_degree',
              'number.bebek_climate_valve_opening_degree',
              'number.misafir_climate_valve_opening_degree'] 
            | map('states') 
            | select('is_number')
            | map('float') 
            | max == 0 }}
        trigger: template
        id: "off"
    conditions: []
    actions:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - heat
            sequence:
              - action: switch.turn_on
                metadata: {}
                data: {}
                target:
                  entity_id: switch.koridor2_switch
          - conditions: []
            sequence:
              - action: switch.turn_off
                metadata: {}
                data: {}
                target:
                  entity_id: switch.koridor2_switch
    mode: restart
