template:
  - sensor:
      - name: yatak_thermostat
        unique_id: yatak_thermostat
        unit_of_measurement: "°C"
        state: "{{ state_attr('climate.yatak_climate_2', 'current_temperature') }}"
        availability: "{{ states('climate.yatak_climate_2') != 'unavailable' }}"
        device_class: temperature

input_number:
  yatak_thermostat:
    name: yatak_thermostat
    initial: 0
    min: 0
    max: 100
    step: 1

automation:
  - alias: "yatak_thermostat"
    id: "yatak_thermostat"
    triggers:
      - trigger: state
        entity_id: input_number.yatak_thermostat
        id: pidvalue
      - trigger: state
        entity_id:
          - climate.yatak_thermostat
    actions:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - pidvalue
            sequence:
              - action: number.set_value
                target:
                  entity_id: number.yatak_climate_2_valve_opening_degree
                data:
                  value: "{{ trigger.to_state.state | int }}"
              - action: number.set_value
                target:
                  entity_id: number.yatak_climate_2_valve_closing_degree
                data:
                  value: "{{ 100 - (trigger.to_state.state | int) }}"
              - action: number.set_value
                target:
                  entity_id: number.yatak_climate_1_valve_opening_degree
                data:
                  value: "{{ trigger.to_state.state | int }}"
              - action: number.set_value
                target:
                  entity_id: number.yatak_climate_1_valve_closing_degree
                data:
                  value: "{{ 100 - (trigger.to_state.state | int) }}"
          - conditions: []
            sequence:
              - action: climate.set_hvac_mode
                metadata: {}
                target:
                  entity_id: "climate.yatak_climate_2"
                data:
                  hvac_mode: "{{states('climate.yatak_thermostat')}}"
              - action: climate.set_temperature
                metadata: {}
                target:
                  entity_id: "climate.yatak_climate_2"
                data:
                  temperature: "{{state_attr('climate.yatak_thermostat', 'temperature')}}"
              - action: climate.set_hvac_mode
                metadata: {}
                target:
                  entity_id: "climate.yatak_climate_1"
                data:
                  hvac_mode: "{{states('climate.yatak_thermostat')}}"
              - action: climate.set_temperature
                metadata: {}
                target:
                  entity_id: "climate.yatak_climate_1"
                data:
                  temperature: "{{state_attr('climate.yatak_thermostat', 'temperature')}}"
    mode: single

climate:
  - platform: smart_thermostat
    name: yatak_thermostat
    unique_id: yatak_thermostat
    heater: input_number.yatak_thermostat
    target_sensor: sensor.yatak_thermostat
    target_temp: 19
    keep_alive:
      seconds: 60
    kp: 60
    ki: 0.01
    kd: 2000
    min_cycle_duration: 10
    pwm: 0
