template:
  - sensor:
      - name: sercan_thermostat
        unique_id: sercan_thermostat
        unit_of_measurement: "°C"
        state: "{{ state_attr('climate.sercan_climate', 'current_temperature') }}"
        availability: "{{ states('climate.sercan_climate') != 'unavailable' }}"
        device_class: temperature

input_number:
  sercan_thermostat:
    name: sercan_thermostat
    initial: 0
    min: 0
    max: 100
    step: 1

automation:
  - alias: "sercan_thermostat"
    id: "sercan_thermostat"
    triggers:
      - trigger: state
        entity_id: input_number.sercan_thermostat
        id: pidvalue
      - trigger: state
        entity_id:
          - climate.sercan_thermostat
    actions:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - pidvalue
            sequence:
              - action: number.set_value
                target:
                  entity_id: number.sercan_climate_valve_opening_degree
                data:
                  value: "{{ trigger.to_state.state | int }}"
              - action: number.set_value
                target:
                  entity_id: number.sercan_climate_valve_closing_degree
                data:
                  value: "{{ 100 - (trigger.to_state.state | int) }}"
          - conditions: []
            sequence:
              - action: climate.set_hvac_mode
                metadata: {}
                target:
                  entity_id: "climate.sercan_climate"
                data:
                  hvac_mode: "{{states('climate.sercan_thermostat')}}"
              - action: climate.set_temperature
                metadata: {}
                target:
                  entity_id: "climate.sercan_climate"
                data:
                  temperature: "{{state_attr('climate.sercan_thermostat', 'temperature')}}"
    mode: single

climate:
  - platform: smart_thermostat
    name: sercan_thermostat
    unique_id: sercan_thermostat
    heater: input_number.sercan_thermostat
    target_sensor: sensor.sercan_thermostat
    target_temp: 19
    keep_alive:
      seconds: 60
    kp: 60
    ki: 0.01
    kd: 2000
    min_cycle_duration: 10
    pwm: 0
